server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.11.237:3306/tourism?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: user
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

  devtools:
    restart:
      enabled: true

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd

  freemarker:
    suffix: .html
    cache: false
    template-loader-path: classpath:/templates


mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.sdgl.pojo

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql











